Make bolt agent an object in intergration tests
neo4j/neo4j-javascript-driver pull request #1092
Opened 2023-06-06 10:10 UTC by ConorNeo

2023-06-06 10:15 UTC, thelonelyvulpes approved these changes
🍰

2023-06-07 07:47 UTC, bigmontz requested changes
We need revert the change on the examples test.

2023-06-07 07:47 UTC, bigmontz commented on packages/neo4j-driver/test/examples.test.js
> +      Notification.createNext('Infinity Gauntlet'),
This change won't solve the issue and also make it more easy to happen. We need a equal comparison which not depends on the order, actually. But for now, we can revert this change.

2023-06-07 08:08 UTC, bigmontz approved these changes
📦

2023-06-07 13:50 UTC, bigmontz reviewed
I might solve the issue with this test.

2023-06-07 13:50 UTC, bigmontz commented on packages/neo4j-driver/test/examples.test.js
> +        "CREATE (:Product {id: item.id, title: item.title})'"
Revert it

2023-06-07 13:50 UTC, bigmontz commented on packages/neo4j-driver/test/examples.test.js
> +    )
```suggestion
    expect(titles.length).toEqual(3)
    expect(people).toContain(
      Notification.createNext('Infinity Gauntlet')
    )
    expect(people).toContain(
      Notification.createNext('Mjölnir')
    )
    expect(people).toContain(
      Notification.createComplete()
    )
```

2023-06-07 13:52 UTC, bigmontz commented on packages/neo4j-driver/test/examples.test.js
> +        "CREATE (:Product {id: item.id, title: item.title})'"
```suggestion
        "UNWIND ['Infinity Gauntlet', 'Mjölnir'] AS item " +
        'CREATE (:Product {id: 0, title: item})'
```

2023-06-07 13:58 UTC, ConorNeo commented on packages/neo4j-driver/test/examples.test.js
> +    expect(titles.length).toEqual(3)
do we mean people.length

2023-06-07 18:18 UTC, merged