Least connected load balancing strategy
neo4j/neo4j-javascript-driver pull request #267
Opened 2017-07-11 10:27 UTC by lutovich

Based on https://github.com/neo4j/neo4j-javascript-driver/pull/265

2017-07-12 15:24 UTC, praveenag approved these changes

2017-07-12 15:26 UTC, praveenag requested changes

2017-07-12 15:26 UTC, praveenag commented on test/v1/routing-driver.test.js
> +
This is missing a test case for `'Unknown load balancing strategy`

2017-07-13 10:28 UTC, lutovich commented
@praveenag test added

2017-07-14 08:40 UTC, merged