Introducing protocol 4.4 and User Impersonation
neo4j/neo4j-javascript-driver pull request #784
Opened 2021-10-07 16:18 UTC by bigmontz

Users can, when they have been granted explicit permission, run transactions against the database as different users. When impersonating a user, the query is run as the complete security context of the impersonated user and not the authenticated user (e.g. home database, permissions etc).

- [x] Create protocol 4.4 version
- [x] Add protocol to the handshake
- [x] Change the messages RUN, BEGIN and ROUTE to support the impersonation parameter
- [x] Add support to the impersonation into the driver surface
- [x] Add special treatments for the default/home database

2021-10-12 14:21 UTC, robsdedude requested changes
Mostly formatting and typos.
However, there are some behavioral concerns. Great PR :guitar:

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/bolt/create.js
> +        chunker,
```suggestion
      return new BoltProtocolV4x4(
        server,
        chunker,
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/bolt/request-message.js
> +   * @param {string} impersonatedUser the impersonated user mode.
```suggestion
   * @param {string} impersonatedUser the impersonated user.
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/bolt/request-message.js
> +   * @param {string} impersonatedUser the impersonated user mode.
```suggestion
   * @param {string} impersonatedUser the impersonated user.
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/bolt/request-message.js
> +   * @param {string} databaseContext.impersonatedUser The name of the user it should it's impersonation to get the routing table.
```suggestion
   * @param {string} databaseContext.impersonatedUser The name of the user to impersonation when getting the routing table.
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/connection-provider/connection-provider-direct.js
> +  constants: { BOLT_PROTOCOL_V4_0, BOLT_PROTOCOL_V3, BOLT_PROTOCOL_V4_4 }
```suggestion
  constants: { BOLT_PROTOCOL_V3, BOLT_PROTOCOL_V4_0, BOLT_PROTOCOL_V4_4 }
```
or 
```suggestion
  constants: { BOLT_PROTOCOL_V4_4 , BOLT_PROTOCOL_V4_0, BOLT_PROTOCOL_V3 }
```
Feel free to ignore me :see_no_evil:

2021-10-12 14:21 UTC, robsdedude commented on packages/core/src/driver.ts
> +
This is being exported for usage in client code, right? Because I think other drivers don't offer something like this.

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/connection-provider/connection-provider-routing.js
> +  }
What's the lifetime of this? The driver should only keep a user's home db cached per session. Not for the entire lifetime of the driver. I think, there is actually no TestKit test covering this :/ If you want, we can develop one together.

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/rediscovery/routing-table.js
> +    routingTableDatabase,
I can't find where this value is being read. What is it used for?

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/bolt/bolt-protocol-v4x4.test.js
> +
```suggestion
```
Exactly the same test as the one above.

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/bolt/request-message.test.js
> +        const impersonatedUser = 'the impostor'
Now that seems a little sus... :x:

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/bolt/request-message.test.js
>  })
Looks like the indentation went wrong at some point.

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +
```suggestion
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/src/connection-provider/connection-provider-routing.js
> +    return database === DEFAULT_DB_NAME? this._homedbs.get(impersonatedUser) : database
```suggestion
    return database === DEFAULT_DB_NAME ? this._homedbs.get(impersonatedUser) : database
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +    it.each(usersDataSet)('should resolve the home database name for the user=%s', (user) => {
I think I haven't seen any tests that make sure that `.resolveDatabaseName` does the right thing if `database` is not `null`.

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +
```suggestion
```

2021-10-12 14:21 UTC, robsdedude commented on packages/core/src/session.ts
> +        database: this._connectionHolderWithMode(this._mode).resolveDatabaseName(), // TODO: Cleanup it || BIGMONTZ
I've found a TODO :smiley:

2021-10-12 14:21 UTC, robsdedude commented on packages/core/src/transaction.ts
> +   * @param {string} args.impersonatedUser - The username which the user wants to impersonate for the duration of the session.
```suggestion
   * @param {string} impersonatedUser - The name of the user which should be impersonated for the duration of the session.
```

2021-10-12 14:21 UTC, robsdedude commented on packages/bolt-connection/test/bolt/bolt-protocol-v4x4.test.js
> +    const impersonatedUser = 'the impostor'
```suggestion
    const impersonatedUser = 'the imposter'
```

Not that it really matters :rofl: (it's also misspelled in other places).

2021-10-12 14:21 UTC, robsdedude commented on packages/neo4j-driver-lite/test/unit/index.test.ts
> +        resolveDatabaseName: ({database}: {database?:string, impersonatedUser?: string}) => database,
Don't know if the first or the seconds variant is the preferred one, but the argument types are not formatted consistently.

2021-10-12 14:21 UTC, robsdedude commented on packages/neo4j-driver/src/driver.js
> +   * @param {string} param.impersonatedUser - The username which the user wants to impersonate for the duration of the session.
```suggestion
   * @param {string} param.impersonatedUser - The name of the user which should be impersonated for the duration of the session.
```

2021-10-12 14:21 UTC, robsdedude commented on packages/neo4j-driver/test/internal/node/direct.driver.boltkit.test.js
> +  describe('should report whether usr impersonation is supported', () => {
```suggestion
  describe('should report whether user impersonation is supported', () => {
```

2021-10-12 14:28 UTC, bigmontz commented on packages/core/src/driver.ts
> +
Yes, it's exported. We have methods for supporting multidb and so on, it's related with the browser usage.

2021-10-12 14:34 UTC, bigmontz commented on packages/bolt-connection/src/rediscovery/routing-table.js
> +    routingTableDatabase,
It's routing table database name, the one comes in the routing table. 

The routing table object already had database property, so I've tried to put a more explanatory name. It is used when the home database name is linked with the user.

2021-10-12 14:44 UTC, bigmontz commented on packages/bolt-connection/src/connection-provider/connection-provider-routing.js
> +  }
It lasts until this user tries acquire connection this database with the impersonated user and all the connection were stale for it. 

I've just realize an issue with this. If this routing table is updated by the default user always, the impersonated user will always have the same home db forever

2021-10-12 14:51 UTC, bigmontz commented on packages/bolt-connection/test/bolt/request-message.test.js
>  })
updated

2021-10-12 14:52 UTC, bigmontz commented on packages/bolt-connection/test/bolt/bolt-protocol-v4x4.test.js
> +    const impersonatedUser = 'the impostor'
I will keep it since the imposto is imposter in portuguese :D

2021-10-12 14:54 UTC, bigmontz commented on packages/neo4j-driver-lite/test/unit/index.test.ts
> +        resolveDatabaseName: ({database}: {database?:string, impersonatedUser?: string}) => database,
Solved

2021-10-12 14:55 UTC, bigmontz commented on packages/bolt-connection/test/bolt/request-message.test.js
> +        const impersonatedUser = 'the impostor'
the imposter is Brazilian.

2021-10-12 15:03 UTC, bigmontz commented on packages/core/src/session.ts
> +        database: this._connectionHolderWithMode(this._mode).resolveDatabaseName(), // TODO: Cleanup it || BIGMONTZ
You missed the other, but the solution for this todo doesn't fit the time we have until the release. It's huge.

2021-10-12 15:31 UTC, robsdedude commented on packages/bolt-connection/test/bolt/bolt-protocol-v4x4.test.js
> +    const impersonatedUser = 'the impostor'
:brazil:

2021-10-14 10:20 UTC, bigmontz commented on packages/bolt-connection/src/connection-provider/connection-provider-routing.js
> +  }
Default DB now is linked to the session

2021-10-14 12:28 UTC, robsdedude approved these changes
LGTM. Some minor comments.

2021-10-14 12:28 UTC, robsdedude commented on packages/core/src/internal/connection-holder.ts
> +    onDatabaseNameResolved
Undocumented argument.

2021-10-14 12:28 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +                routingTableDatabase: 'homedb'
```suggestion
              database: null,
              routers: [server1, server2, server3],
              readers: [server1, server2],
              writers: [server3],
              user,
              routingTableDatabase: 'homedb'
```

2021-10-14 12:28 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +                routingTableDatabase: 'databaseB'
```suggestion
              database: 'databaseA',
              routers: [server1, server2, server3],
              readers: [server1, server2],
              writers: [server3],
              user,
              routingTableDatabase: 'databaseB'
```

2021-10-14 12:28 UTC, robsdedude commented on packages/bolt-connection/test/connection-provider/connection-provider-routing.test.js
> +                routingTableDatabase: 'homedb'
```suggestion
              database: null,
              routers: [server1, server2, server3],
              readers: [server1, server2],
              writers: [server3],
              user,
              routingTableDatabase: 'homedb'
```

2021-10-14 12:28 UTC, robsdedude commented on packages/core/src/connection-provider.ts
> +   * @param {function (params:string?)} params.onDatabaseNameResolved - Callback called when the database name get resolved
either `params` or `param`.

2021-10-14 13:34 UTC, robsdedude approved these changes
:smiling_imp:

2021-10-14 15:13 UTC, merged