Fix some TypeScript errors found with TypeScript 4.5 / Deno
neo4j/neo4j-javascript-driver pull request #829
Opened 2021-12-23 03:46 UTC by bradenmacdonald

While I was working on [a Deno driver for Neo4j that uses this codebase](https://deno.land/x/neo4j_lite_client@4.4.1-preview), I ran into some Typescript errors which this PR fixes.

These could be only relevant with the newer version of TypeScript (4.5) or with Deno, but I tried to fix them in a way that will work with Node and older versions of TypeScript without issues.

I'll put explanations of each change inline.

2021-12-23 03:46 UTC, bradenmacdonald commented on packages/core/src/connection.ts
> +  databaseId: string = ""
This fixes:
`"Property 'id' has no initializer and is not definitely assigned in the constructor."`

2021-12-23 03:47 UTC, bradenmacdonald commented on packages/core/src/internal/connection-holder.ts
> +      .then((connection?: Connection|void) => {
This fixes:

```
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type '(connection?: Connection | undefined) => Promise<void>' is not assignable to parameter of type '(value: void | Connection) => void | PromiseLike<void>'.
  Types of parameters 'connection' and 'value' are incompatible.
    Type 'void | Connection' is not assignable to type 'Connection | undefined'.
      Type 'void' is not assignable to type 'Connection | undefined'.
      .then((connection?: Connection) => {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2021-12-23 03:47 UTC, bradenmacdonald commented on packages/core/src/internal/observers.ts
> +    func.bind(thisArg)(param as any)
This fixes:

```
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type 'T | undefined' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'T | undefined'.
    func.bind(thisArg)(param)
```

2021-12-23 03:49 UTC, bradenmacdonald commented on packages/core/src/internal/transaction-executor.ts
> +  private _inFlightTimeoutIds: Timeout[]
The type `NodeJS.Timeout` is (obviously) specific to Node, and will cause an error in Deno.

Using `ReturnType<typeof setTimeout>` gives the same effect in Node but is also compatible with Deno (or any other runtime).

2021-12-23 03:51 UTC, bradenmacdonald commented on packages/neo4j-driver-lite/src/index.ts
> +        console.log(`${globalThis.Date.now()} ${level.toUpperCase()} ${message}`)
`global` isn't defined in Deno and will cause an error.

[`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) works in Node (v12+) and Deno.

2021-12-29 12:14 UTC, bigmontz requested changes
Thanks for your contribution.

The PR looks good, but the compatibility break with Node 10 should be resolved before the PR get merged. Moving the `logging` to a file call `logging.ts` should solve the naming conflict.

2021-12-29 12:14 UTC, bigmontz commented on packages/neo4j-driver-lite/src/index.ts
> +        console.log(`${globalThis.Date.now()} ${level.toUpperCase()} ${message}`)
We'd like to keep compatibility with Node v10, since it stills the one installed by `apt get` in Ubuntu LTS.  If you move this object declaration to it own file, it won't have any name conflict and then we will could use `Date.now()` without need any access to the global object.

2021-12-29 17:59 UTC, bradenmacdonald commented on packages/neo4j-driver-lite/src/index.ts
> +        console.log(`${globalThis.Date.now()} ${level.toUpperCase()} ${message}`)
Sure thing. I've pushed a commit to move it to `logging.ts` as you suggested.

2021-12-29 18:49 UTC, bradenmacdonald commented
Hmm, I see there is now a CI error but I'm not sure what it is.

2021-12-30 09:46 UTC, bigmontz approved these changes
🎹 

Thanks for your contribution.

2021-12-30 10:31 UTC, merged